# Generated by Django 6.0.7 on 2026-08-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('rrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='РРЦ')),
                ('base_cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Базовая себестоимость')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Габариты (ШxВxГ)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес (кг)')),
                ('min_stock', models.PositiveIntegerField(default=0, verbose_name='Мин. остаток')),
                ('grill_type', models.CharField(blank=True, choices=[('charcoal', 'Угольный'), ('gas', 'Газовый'), ('ceramic', 'Керамический')], max_length=20, null=True, verbose_name='Тип гриля')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='catalog.productcategory', verbose_name='Категория')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='catalog.supplier', verbose_name='Поставщик')),
            ],
            options={
                'db_table': 'product_cards',
                'indexes': [models.Index(fields=['category'], name='idx_products_category'), models.Index(fields=['sku'], name='idx_products_sku')],
            },
        ),
    ]
