# Generated by Django 6.1 on 2026-09-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_grilltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='sku',
            field=models.CharField(max_length=50, verbose_name='Артикул'),
        ),
    ]
