# Generated by Django 6.0.7 on 2026-08-02 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'db_table': 'delivery_services',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'db_table': 'payment_types',
            },
        ),
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'db_table': 'sales_channels',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(unique=True, verbose_name='Номер заказа')),
                ('order_date', models.DateField(verbose_name='Дата заказа')),
                ('status', models.CharField(choices=[('reserved', 'Резерв'), ('confirmed', 'Подтвержден'), ('in_delivery', 'В доставке'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='reserved', max_length=20, verbose_name='Статус')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Трек-номер')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clients.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('delivery_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.deliveryservice', verbose_name='Служба доставки')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders_as_seller', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.saleschannel', verbose_name='Канал продаж')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Себестоимость')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена без НДС')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Ставка НДС (%)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
                ('product_card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_items', to='catalog.productcard', verbose_name='Товар')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Заказ')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.paymenttype', verbose_name='Способ оплаты')),
            ],
            options={
                'db_table': 'order_payments',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='idx_orders_date'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller'], name='idx_orders_seller'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client'], name='idx_orders_client'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='idx_orders_status'),
        ),
    ]
