# Generated by Django 6.1 on 2026-08-16 20:49

import django.db.models.deletion
from django.db import migrations, models


def copy_order_delivery_fields(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderDelivery = apps.get_model('orders', 'OrderDelivery')
    rows = []
    for order in Order.objects.exclude(delivery_service_id=None).iterator():
        rows.append(OrderDelivery(
            order_id=order.pk,
            delivery_service_id=order.delivery_service_id,
            tracking_number=order.tracking_number or '',
        ))
    if rows:
        OrderDelivery.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Трек-номер')),
                ('delivery_service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='orders.deliveryservice', verbose_name='Служба доставки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'db_table': 'order_deliveries',
            },
        ),
        migrations.RunPython(copy_order_delivery_fields, migrations.RunPython.noop),
    ]
