# Generated by Django 6.1 on 2026-08-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доставки'),
        ),
    ]
