# Generated by Django 6.1 on 2026-08-16 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdelivery_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sales_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='orders.saleschannel', verbose_name='Канал продаж'),
        ),
    ]
