# Generated by Django 6.1 on 2026-09-01 15:33

from django.db import migrations, models


SYSTEM_STATUSES = [
    ('reserved', 'Резерв', 'open', 10),
    ('confirmed', 'Подтвержден', 'open', 20),
    ('in_delivery', 'В доставке', 'open', 30),
    ('completed', 'Завершен', 'completed', 40),
    ('cancelled', 'Отменен', 'cancelled', 50),
]


def seed_system_statuses(apps, schema_editor):
    OrderStatus = apps.get_model('orders', 'OrderStatus')
    for code, name, kind, sort_order in SYSTEM_STATUSES:
        OrderStatus.objects.get_or_create(
            code=code,
            defaults={
                'name': name,
                'kind': kind,
                'sort_order': sort_order,
                'is_system': True,
            },
        )


def unseed_system_statuses(apps, schema_editor):
    OrderStatus = apps.get_model('orders', 'OrderStatus')
    OrderStatus.objects.filter(
        code__in=[code for code, *_rest in SYSTEM_STATUSES],
        is_system=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_seller_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('kind', models.CharField(choices=[('open', 'Открытый'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='open', max_length=20, verbose_name='Тип')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системный')),
            ],
            options={
                'db_table': 'order_statuses',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_system_statuses, unseed_system_statuses),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='reserved', max_length=32, verbose_name='Статус'),
        ),
    ]
