# Generated by Django 6.0.7 on 2026-08-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Остаток')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('stock_tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тег')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_card', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_items', to='catalog.productcard', verbose_name='Карточка товара')),
            ],
            options={
                'db_table': 'stock_items',
                'indexes': [models.Index(fields=['stock_tag'], name='idx_stock_tag')],
            },
        ),
    ]
