# Generated by Django 6.1 on 2026-09-02 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_boards_for_existing_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Board = apps.get_model('tasks', 'Board')
    List = apps.get_model('tasks', 'List')
    defaults = (
        ('todo', 'К работе', 0),
        ('doing', 'В работе', 1),
        ('done', 'Готово', 2),
    )
    for user in User.objects.all().iterator():
        board, _ = Board.objects.get_or_create(owner_id=user.pk)
        for code, name, sort_order in defaults:
            List.objects.get_or_create(
                board=board,
                code=code,
                defaults={'name': name, 'sort_order': sort_order},
            )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_client_grill_type'),
        ('orders', '0007_orderstatus_and_status_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_board', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'db_table': 'task_boards',
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='tasks.board', verbose_name='Доска')),
            ],
            options={
                'db_table': 'task_lists',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_cards', to='clients.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_task_cards', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_cards', to='orders.order', verbose_name='Заказ')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tasks.list', verbose_name='Колонка')),
            ],
            options={
                'db_table': 'task_cards',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['board'], name='idx_task_lists_board'),
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(fields=('board', 'code'), name='uniq_task_list_board_code'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['list', 'position'], name='idx_task_cards_list_pos'),
        ),
        migrations.RunPython(seed_boards_for_existing_users, migrations.RunPython.noop),
    ]
