# Generated by Django 6.0.7 on 2026-08-02 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('purchase_category', models.CharField(blank=True, max_length=10, null=True, verbose_name='Категория покупки')),
                ('first_purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата первой покупки')),
                ('last_purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата последней покупки')),
                ('grill_type', models.CharField(blank=True, choices=[('charcoal', 'Угольный'), ('gas', 'Газовый'), ('ceramic', 'Керамический')], max_length=20, null=True, verbose_name='Тип гриля')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Общий бюджет')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)')),
                ('preferred_contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Предпочитаемый контакт')),
                ('acquisition_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник привлечения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'indexes': [models.Index(fields=['last_name'], name='idx_clients_last_name'), models.Index(fields=['purchase_category'], name='idx_clients_purchase_cat')],
            },
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'db_table': 'client_phones',
            },
        ),
    ]
