# Generated by Django 6.1 on 2026-09-02 20:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vacation', 'Отпуск'), ('time_off', 'Отгул')], max_length=16, verbose_name='Тип')),
                ('date_from', models.DateField(verbose_name='С')),
                ('date_to', models.DateField(verbose_name='По')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_personnel_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'db_table': 'personnel_leaves',
                'indexes': [models.Index(fields=['user'], name='idx_personnel_leaves_user'), models.Index(fields=['date_from', 'date_to'], name='idx_personnel_leaves_range')],
            },
        ),
        migrations.CreateModel(
            name='MonthEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц')),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Часы')),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Бонус')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ставка часа')),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Процент с продаж')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_months', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'db_table': 'personnel_months',
                'indexes': [models.Index(fields=['year', 'month'], name='idx_personnel_months_ym')],
                'constraints': [models.UniqueConstraint(fields=('user', 'year', 'month'), name='uniq_personnel_month_user')],
            },
        ),
    ]
