# Generated by Django 6.1 on 2026-09-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='modules',
            field=models.JSONField(blank=True, default=list, verbose_name='Доступы'),
        ),
    ]
